//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyrsovKpo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual SupplyDetails SupplyDetails { get; set; }
    }
}
